### ISSUE TITLE
CF LDV does not increment

### ISSUE THREAD

**Issue by jsheradin** [Pheeeeenom/KeBlowFusePatchGenerator#1]
Expected result: LDV at fuse line 7 is non-zero

Actual result: LDV at fuse line 7 stays at 0

Motherboard: Xenon
Image type: JTAG
Fuse line 1: Phat Retail
Fuse line 2: 0
CPU key: Matches processor
Update Sequence: I've tried 1, 2, and 8

Current fuse set:
```
fuseset 00: c0ffffffffffffff
fuseset 01: 0f0f0f0f0f0f0ff0
fuseset 02: 0000000000000000
fuseset 03: 0235a186d5e72a68
fuseset 04: 0235a186d5e72a68
fuseset 05: f70ac9dbd5923679
fuseset 06: f70ac9dbd5923679
fuseset 07: 0000000000000000
fuseset 08: 0000000000000000
fuseset 09: 0000000000000000
fuseset 10: 0000000000000000
fuseset 11: 0000000000000000
```

Jrunner is Octal's 3.3.0. It builds the NAND and gives the warning about being patched to blow fuses. Running the xex gives no errors apart from freezing once you confirm the blow. Waiting about 30 seconds and power cycling to xell reveals no LDV fuses blown.

CPU was a zero fuse. I blew the CPU key and retail line using a DEVGL patch for a Jasper. Some files were moved around to make it use the Xenon SMC. I'm 90% sure I had LDV set to 1 when making the patch but I don't recall for sure.

**Comment by jsheradin** [comment]
The current JTAG images were built using an untouched copy of Octal's Jrunner. The JTAG patch from KEBFPG "patches_xenon.bin" was dropped into `Jrunner>xeBuild>17559>bin` and overwrote the existing file. Image was built in Jrunner as JTAG on dash 17559 and flashed to the console. Jrunner gave the fuse patch warning after building.

**Comment by Pheeeeenom** [comment]
You're correct, there is an issue. May I ask what you specifically want to set it to and I'll make you a file

**Comment by jsheradin** [comment]
Thanks for the quick reply!

I'd like to boot a retail 6717 and eventually downgrade that to 1888 (Degraded 1.1). I believe it is doable with CBLDV = 0 and CDLDV = 1. Patch file would be for the JTAG image.

Thanks!

**Comment by Pheeeeenom** [comment]
I made a new release for you. 1.2. Should fix your issue. Please test it out. Thanks!

**Comment by jsheradin** [comment]
6BL LDV is now 1!

Thanks for the quick support!
