### ISSUE TITLE
CB LDV between 0 and 13 does not generate a patch file

### ISSUE THREAD

**Issue by jsheradin** [Pheeeeenom/KeBlowFusePatchGenerator#2]
Entering anything between 0 and 13 for Fuse Line 2 (CB LDV) does not generate a patch file. It does not matter if I click yes or no at the warning prompt. If 'Auto-Apply' is checked it will result in an empty file. Results are the same in both current and previous releases.

Motherboard: Xenon
Image Type: JTAG
Fuse Line 1: Phat Retail
Fuse Line 2 (CB LDV): See below
CPU Key: Correct
Update Sequence: I tried 0 and 1

CB LDV inputs:
0 - Output file is generated
**1 through 12 - Additional warning box, no output file**
13 through 16 - Additional serious warning box, output file is generated
17 or larger - CB too big message

Thanks!

**Comment by Pheeeeenom** [comment]
fixed, was a typo on a check. please try 1.3

**Comment by jsheradin** [comment]
Patches now generate!

Thanks again!
